### ISSUE TITLE
Runtime error: Error: Cannot find module 'expect'

### ISSUE THREAD

**Issue by lc3t35** [Sanjo/meteor-wallaby-sandbox#1]
Hi Sanjo, how do you configure the sandbox for "expect" module to be find ?

```
Thu, 31 Dec 2015 19:40:55 GMT wallaby:workers Running tests in sandbox [worker #0, session #enl9g]
Thu, 31 Dec 2015 19:40:55 GMT wallaby:workers Sandbox (active) [enl9g] error: Error: Cannot find module 'expect'
Thu, 31 Dec 2015 19:40:55 GMT wallaby:workers Failed to map the stack to user code, entry message: Error: Cannot find module 'expect', stack: Error: Cannot find module 'expect'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at Module.s.require (/Users/laurent/Library/Caches/WebStorm11/wallaby/wallaby/server.js:18:9467)
    at require (module.js:380:17)
    at eval (eval at <anonymous> (/Users/laurent/Library/Caches/WebStorm11/wallaby/wallaby/runners/node/bootstrap.js:14:1006), <anonymous>:10:22)
Runtime error: Error: Cannot find module 'expect'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
```

Thank you ! Happy new year ;)

**Comment by ghost** [comment]
Just do:

```
npm install expect
```

I have worked on super fast unit tests with Wallaby for our Meteor app last week. I will soon make it open source here: https://github.com/xolvio/automated-testing-best-practices, after I have used it a bit.

The apporach in this repository is relatively slow, because it depends on the Meteor build tool. It also has probably some stability problems.

**Comment by lc3t35** [comment]
ok the error is gone after "npm install expect" in tests directory.
